<?php

namespace Jasoft\Viringo\SecurityBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SystemLocalUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemLocalUserRepository extends EntityRepository
{
}
