<?php

namespace Jasoft\Viringo\CoreBundle\Repository;

/**
 * SystemConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemConfigRepository extends EntityRepository
{
}
